apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurya-backend
  namespace: custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aurya-backend
  template:
    metadata:
      labels:
        app: aurya-backend
    spec:
      serviceAccountName: aurya-backend-sa
      containers:
      - name: backend
        image: 248189947068.dkr.ecr.us-east-1.amazonaws.com/aurya-backend-v2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: aurya-config
        - secretRef:
            name: aurya-secret
        env:
        - name: LANGCHAIN_TRACING_V2
          value: "false"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: aurya-backend-svc
  namespace: custom
spec:
  selector:
    app: aurya-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
