apiVersion: v1
kind: ConfigMap
metadata:
  name: aurya-config
  namespace: custom
data:
  LLM_PROVIDER: "bedrock"
  AWS_DEFAULT_REGION: "us-east-1"
  TRINO_HOST: "trino.dataiesb.com"
  TRINO_PORT: "443"
  TRINO_USER: "aurya"
  FUNASA_TRINO_CATALOG: "seaweedfs"
