apiVersion: v1
kind: Secret
metadata:
  name: aurya-secret
  namespace: custom
type: Opaque
stringData:
  POSTGRES_USER: "data_iesb"
  POSTGRES_PASSWORD: "iesb"
  DATABASE_URL: "postgresql://data_iesb:iesb@bigdata.dataiesb.com:5432/iesb"
