apiVersion: v1
kind: ServiceAccount
metadata:
  name: aurya-backend-sa
  namespace: custom
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::248189947068:role/aurya-secrets-role
    # OIDC: oidc.eks.us-east-1.amazonaws.com/id/981120A344AA0AEA960F5A6203814F44
    # Namespace: custom
